readme.md
Changes:
- Added "Project Objective" section to readme.md
=> Updated readme with the project objective

readme.md
The project has been changed from a travel planner to a chrome extension for saving blocks of text. These changes will update our readme documentation to reflect this change.
=> Updated readme information to describe current project

web-app/.gitignore, web-app/package-lock.json, web-app/package.json, web-app/src/App.js, web-app/src/components/LoginButton.js, web-app/src/components/LogoutButton.js, web-app/src/components/Profile.js, web-app/src/index.js
- Set up basic login, logout, sign up functionality
- You can create an account with a test email (i.e. `mar_test@mail.com`)
- or, you can create an account with gmail
- You can see the list of users stored in Auth0 under the **User Management > Users**.
- Get `.env` file from Marielle, whcih contains the client id and domain that React uses to connect to Auth0
- `npm start`
- visit `localhost:3000` should take you to a page with login button.
- if you can create an account, login, and logout, you did it!
https://user-images.githubusercontent.com/24909769/155259349-2dae7102-e600-44f0-8024-e4d57a93523c.mp4
=> Setup Auth0 with React App

.gitignore, web-app/src/App.js
Fixed an error in the App.js that prevented the web app from running.
=> Fixed App.js error

web-app/.eslintrc.yml, web-app/README.md, web-app/package-lock.json, web-app/src/App.js
- Set up ESLint
- Added quick start instructions on how to run the web application locally 
- #42
=> Set up ESLint 

.github/workflows/linter.yml, back-end/package-lock.json, front-end/.eslintrc.yml, front-end/package-lock.json, front-end/src/components/LoginButton.js, package-lock.json
This is to make sure that our format is consistent throughout the project.
This will automatically run linter on a github server provided by github actions.
This workflow will trigger when doing a pull request to develop.
=> Create linter action for ESLint

front-end/src/App.js, front-end/src/index.js
- This removed the landing page (login button).
- When a user is not authenticated, they will be redirected to the login modal.
- I added a new env variables in front end. (see discord)
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> remove landing page to redirect directly to login modal

front-end/public/eventPage.js
Fixes the error where a context menu item would be created when it already existed in the menu
closes #57 
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> All context menu items are now removed before new ones are created

back-end/__tests__/accounts.test.js, back-end/objects/workspace.js, back-end/package-lock.json, back-end/package.json, back-end/server.js
- Created unit tests for the `Account` object, including tests for the HTTP requests and the schema
1. `cd back-end`
2. `npm install`
3. `npm run test`
4. All tests should pass!
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> Added backend unit tests for Account object

front-end/src/atoms/TextBox.js, front-end/src/molecules/TextList.js
- remove function on text box will remove item from web app as well as the database.
- do usual runs for front-end and back-end: `npm start`
- press the remove button and check if text box is now removed from the page as well as in the database
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> Remove function works synchronously on web app

.github/workflows/frontend-tests.yml, front-end/src/__tests__/App.test.js
- Edited execution file (`frontend-tests.yml`) so that frontend tests run
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> Edit CI job to run frontend tests

README.md
- Add video of our project in README.md
- see `readme.md`
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> Add video of our project in README.md

README.md
add refactor ad an issue type in branching rule
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> add refactor ad an issue type in branching rule

front-end/src/organisms/WorkspaceSettings.js
see video:
https://user-images.githubusercontent.com/24909769/159816282-4684eda0-ee54-4fe8-8c01-305835e8f465.mp4
closes #125
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> add collab icon functionality #125

front-end/src/organisms/WorkspaceSettings.js
When editing a workspace pressing the trash icon next to a collaborator's email will remove them from the list. Please note that this won't update the system yet even after pressing save, as that will be a different feature.
closes #129 
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> Added the ability to remove collaborators from a workspace

back-end/__tests__/accounts.test.js, back-end/__tests__/texts.test.js, back-end/__tests__/workspaces.test.js
- Fixed the commented out backend tests
1. Go to the backend folder
2. `npm test`
3. OR see that this PR's checks are passing
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> Fixed failing backend tests

front-end/src/atoms/TextBox/TextBox.css, front-end/src/atoms/TextBox/TextBox.js, front-end/src/atoms/icons.js
- Changes copy on click feedback from an alert window to a toolip
- This also fixes #143 since it will always show the text regardless of copied/not copied state
- closes: #115 
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> Change copy on click feedback

front-end/src/App.js, front-end/src/molecules/SidebarWorkspace.js
- Stay in the same current workspace on refresh
- Closes #148
https://user-images.githubusercontent.com/24909769/161399188-697a813a-6666-4b2a-b85d-81b33669b78f.mp4
- run frontend
- have more than two workspaces in your account
- go to a workspace that is **not the first**
- reload
- This should retain the old workspace.
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> Stay on same current workspace on refresh

back-end/persistence/accounts.js, back-end/persistence/workspaces.js, front-end/src/atoms/DeleteButton.js, front-end/src/molecules/ConfirmationPopup.js, front-end/src/organisms/Sidebar.js, front-end/src/organisms/WorkspaceSettings.js, front-end/src/pages/Dashboard.js, front-end/src/util/requests.js
- Deleting a workspace will delete it from the database along with its texts. The accounts that own or are a collaborator of the workspace will be updated as well.
1. Add a collaborator to a workspace.
2. Delete the workspace.
3. The workspace should be deleted for the owner and collaborator(s).
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> Delete workspace from database

front-end/public/background.js, front-end/src/organisms/WorkspaceSettings.js, front-end/src/pages/Dashboard.js
- Fixed web app error (uncaught Promise) 
- Fixed context menu updating on delete workspace
closes #179 
- freshly reload everything (backend, frontend, extension build)
- add new workspace and check extension for update
- delete workspace and check extension for update
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> Fixed some bugs and errors.

.github/workflows/docker-upload.yml, .gitignore, DOCKER_README.md, back-end/backend.dockerfile, docker-compose.yml, front-end/frontend.dockerfile
Updates the docker files and docker upload yml to build and push app to docker automatically.
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> Build and Push app to Docker repository

readme.md
- Reviewers
- Assignee
- Labels
- Project
- Milestone
=> Fix README conflict between main and develop
